CREATE TABLE IF NOT EXISTS books (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	ISBN VARCHAR(20) UNIQUE NOT NULL,
	title VARCHAR(255) NOT NULL,
	edition VARCHAR(255),
	authors TEXT NOT NULL,
	link VARCHAR(300),
	cover_picture VARCHAR(255) DEFAULT "imgs/books_cover/default_book_cover.png" NOT NULL,
	rating DECIMAL(3,2) DEFAULT 0
);
